/* Generated By:JavaCC: Do not edit this line. preProcessConstants.java */
package preProcess;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface preProcessConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INCLUDE_FILE = 7;
  /** RegularExpression Id. */
  int ANY_THING = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INCLUDE_FILE>",
    "<ANY_THING>",
  };

}
